# Generated by Django 6.0.3 on 2026-03-27 00:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('created_at', models.DateTimeField(verbose_name='Created At')),
                ('modified_at', models.DateTimeField(verbose_name='Last Modified At')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('body', models.TextField(verbose_name='Body')),
                ('created_at', models.DateTimeField(verbose_name='Created At')),
                ('modified_at', models.DateTimeField(verbose_name='Last Modified At')),
                ('published_at', models.DateTimeField(verbose_name='Published At')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.author', verbose_name='Author')),
            ],
        ),
    ]
